# Generated by Django 4.1.5 on 2023-05-11 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Qbank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('question_text', models.TextField()),
                ('options', models.JSONField()),
                ('year_of_study', models.IntegerField()),
                ('unit', models.CharField(max_length=50)),
                ('question_type', models.CharField(choices=[('SAQ', 'Short Answer Questions (SAQs)'), ('MCQ', 'Multiple Choice Questions (MCQs)'), ('ESSAY', 'Essays'), ('VIVA', 'Vivas (Orals)'), ('OSCE', 'OSCEs')], max_length=50)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('tag', models.ManyToManyField(to='qbank.tag')),
            ],
        ),
    ]
