# Generated by Django 4.1.5 on 2023-05-11 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qbank', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qbank',
            old_name='options',
            new_name='question_response',
        ),
        migrations.AlterField(
            model_name='qbank',
            name='unit',
            field=models.IntegerField(choices=[(1, 'Anatomy'), (2, 'Biochemistry'), (3, 'Pathology'), (4, 'Internal Medicine'), (5, 'Psychiatry'), (6, 'Pharmacology')]),
        ),
        migrations.AlterField(
            model_name='qbank',
            name='year_of_study',
            field=models.IntegerField(choices=[(1, 'First year (I)'), (2, 'Second year (II)'), (3, 'Third year (III)'), (4, 'Fourth year (IV)'), (5, 'Fifth year (V)'), (6, 'Sixth year (VI)')]),
        ),
    ]
