# Generated by Django 4.1.5 on 2023-03-14 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qbank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='qBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionId', models.CharField(max_length=100)),
                ('questionText', models.TextField()),
                ('options', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('yearOfStudy', models.IntegerField()),
                ('unit', models.CharField(max_length=100)),
                ('questionType', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='AmayoLifeStory',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='question',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='dataanalysis',
            name='category',
        ),
        migrations.RemoveField(
            model_name='imagevideoquestion',
            name='course',
        ),
        migrations.RemoveField(
            model_name='multiplechoicequestion',
            name='course',
        ),
        migrations.DeleteModel(
            name='Philosophy',
        ),
        migrations.RemoveField(
            model_name='question',
            name='course',
        ),
        migrations.DeleteModel(
            name='ResearchIntroduction',
        ),
        migrations.RemoveField(
            model_name='researchmethodology',
            name='category',
        ),
        migrations.RemoveField(
            model_name='researchresource',
            name='category',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='result',
            name='question',
        ),
        migrations.RemoveField(
            model_name='result',
            name='user',
        ),
        migrations.RemoveField(
            model_name='shortanswerquestion',
            name='course',
        ),
        migrations.RemoveField(
            model_name='studentresearch',
            name='category',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='course',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='DataAnalysis',
        ),
        migrations.DeleteModel(
            name='ImageVideoQuestion',
        ),
        migrations.DeleteModel(
            name='MultipleChoiceQuestion',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='ResearchCategory',
        ),
        migrations.DeleteModel(
            name='ResearchMethodology',
        ),
        migrations.DeleteModel(
            name='ResearchResource',
        ),
        migrations.DeleteModel(
            name='Resource',
        ),
        migrations.DeleteModel(
            name='Result',
        ),
        migrations.DeleteModel(
            name='ShortAnswerQuestion',
        ),
        migrations.DeleteModel(
            name='StudentResearch',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
